import React from 'react';
// Import Swiper React components
import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';

const TestimonialSlider = () => {
    return (
        <Swiper className="text-white"
            spaceBetween={50}
            slidesPerView={3}
            onSlideChange={() => console.log('slide change')}
            onSwiper={(swiper) => console.log(swiper)}
            breakpoints={{
                // when window width is >= 640px
                640: {
                    width: 640,
                    slidesPerView: 1,
                },
                // when window width is >= 768px
                768: {
                    width: 768,
                    slidesPerView: 2,
                },
            }}
        >
        >
            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>

            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>

            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>

            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>
            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>
            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>
            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>
            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>
            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>
            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>
            <SwiperSlide>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore illo cumque pariatur earum quasi accusamus. Ut odio est quo repudiandae sequi aliquid, ab assumenda praesentium! Consectetur qui tenetur quisquam, voluptatem molestias harum obcaecati enim omnis quas! Voluptatem, quisquam reprehenderit odit iste harum delectus vel autem recusandae sint consequatur sequi rem repellendus maxime ut ullam sed omnis veritatis ducimus doloremque hic magni perspiciatis ipsum aliquam excepturi. Delectus ab ad quas consequuntur sapiente, mollitia quod praesentium optio fugit iste sit illo assumenda hic. Ipsa, esse deserunt quaerat dolorem architecto quidem sunt mollitia quo minus atque molestiae ullam! Voluptates exercitationem optio laboriosam ut error sapiente a repudiandae maiores! Quod at, ad corrupti quasi id asperiores autem incidunt blanditiis recusandae eligendi consequatur aliquid maxime unde repudiandae perferendis? Possimus in magnam autem eius illum optio mollitia esse quae praesentium dolore! Culpa accusantium eveniet excepturi cum expedita facilis dolore ipsum optio aut, repudiandae iusto dolores temporibus, ipsa praesentium aperiam mollitia laboriosam necessitatibus quisquam et vitae! Architecto, accusamus quidem officia commodi dolor eos ullam dolorem qui, eveniet sequi quia vero ducimus nihil repellat ipsum natus rem, est corporis neque. Perspiciatis ipsa velit porro eaque aperiam nihil reprehenderit rerum quas explicabo deserunt, culpa blanditiis magni praesentium animi odio.</SwiperSlide>

            ...
        </Swiper>
    );
};

export default TestimonialSlider;